### PR TITLE
Add data-modules and associations

### PR DESCRIPTION
**Pull request by CrystallineButterfly**
Hello there, Thank you for the review 🦋

This PR includes the completion of the following: 

🧿 Create a new app. Give it a meaningful name ✅
🧿 Initialize your project with Git ✅
🧿 Make sure that your project has a Postgres database set up ✅
🧿 Build your project schema ✅
🧿 Create and run the necessary migration files ✅
🧿 Table and column names should match the ERD diagram ✅
🧿 Note: photo for the users table should be a link to an image ✅
🧿 Foreign keys should be included ✅
🧿 All columns that are foreign keys should have a corresponding index ✅

 🚀 All the best- K  🚀

### CODE REVIEW

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
Hi 👋 @CrystallineButterfly, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- The PR title and description looks professional ✔️
- No linter errors ✔️
- Descriptive commit messages ✔️


## Required Changes ♻️
_Check the comments under the review._

- [x] Kindly work on the readme file, customize it and make it look professional.
- [ ] The project was about adding data to models, unfortunately, I can't see any model in your app.  Please revisit the requirements for the project again.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by thecodechaser — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @CrystallineButterfly👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️



## Required Changes ♻️

- [x] Great job using the professional README template. Please customize the file with the correct project title, description, and steps to set up the project and add your social handles, It will make your README file looks more professional.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by CrystallineButterfly** [comment]
Hi there @thecodechaser Thank you bro! Good to hear from you, I have updated it now!

**Comment by CrystallineButterfly** [comment]
Hi @elisha2kyakpo1 Thank you for the review, and my bad I sent this PR for review on the wrong one, this is for the first project.

**Review by AnselemOdims — APPROVED** [review]
### Hi  @CrystallineButterfly 🙋‍♀️, 
Good job in making the required changes 👏 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by CrystallineButterfly** [comment]
Thank you bro!

**Pull request merged**
